// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNOpyIvhWBC7A9h8GcbHND3uEj6WtFb58',
    appId: '1:435192725858:web:a51c0299e795900af86c3b',
    messagingSenderId: '435192725858',
    projectId: 'aistudy-a658e',
    authDomain: 'aistudy-a658e.firebaseapp.com',
    storageBucket: 'aistudy-a658e.firebasestorage.app',
    measurementId: 'G-30EJCGCM1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpZR_aGgCsZR-piVEMUDEr6pWdAlwbL7U',
    appId: '1:435192725858:android:4947538ce29f02bdf86c3b',
    messagingSenderId: '435192725858',
    projectId: 'aistudy-a658e',
    storageBucket: 'aistudy-a658e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuU7a_55MpP_rJ8YmtT1h2PiXYIQz2Rfk',
    appId: '1:435192725858:ios:619f8bd057996d0ef86c3b',
    messagingSenderId: '435192725858',
    projectId: 'aistudy-a658e',
    storageBucket: 'aistudy-a658e.firebasestorage.app',
    iosBundleId: 'com.example.fypAistudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuU7a_55MpP_rJ8YmtT1h2PiXYIQz2Rfk',
    appId: '1:435192725858:ios:619f8bd057996d0ef86c3b',
    messagingSenderId: '435192725858',
    projectId: 'aistudy-a658e',
    storageBucket: 'aistudy-a658e.firebasestorage.app',
    iosBundleId: 'com.example.fypAistudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNOpyIvhWBC7A9h8GcbHND3uEj6WtFb58',
    appId: '1:435192725858:web:1b2248c630fb5a87f86c3b',
    messagingSenderId: '435192725858',
    projectId: 'aistudy-a658e',
    authDomain: 'aistudy-a658e.firebaseapp.com',
    storageBucket: 'aistudy-a658e.firebasestorage.app',
    measurementId: 'G-PJK0PGYP27',
  );
}
